version: '3'

#
services:

  db:
    image: postgres:15-bullseye
    ports:
      - 5432:5432
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - POSTGRES_USER=fastladder
      - POSTGRES_PASSWORD=fastladder
      - POSTGRES_DB=fastladder
    # volumes:
    #   - ./pgsql:/var/lib/postgresql/data
  web:
    build: .
    env_file: env.production
    command: bash -c "bundle exec unicorn -p 3001 -c ./config/unicorn.rb"
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: always
  crawler:
    build: .
    env_file: env.production
    command: bash -c "bundle exec ruby script/crawler"
    depends_on:
      - db
    restart: always

