version: '3'

#
services:
   db:
     image: mysql:8
     command: --default-authentication-plugin=mysql_native_password
     volumes:
       - ./data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: fastladder
       MYSQL_DATABASE: fastladder
       MYSQL_USER: fastladder
       MYSQL_PASSWORD: fastladder1234
   web:
     build: .
     env_file: env.production
     command: bash -c "bundle exec unicorn -p 3001 -c ./config/unicorn.rb"
     ports:
       - "3001:3001"
     depends_on:
       - db
     restart: always
   crawler:
     build: .
     env_file: env.production
     command: bash -c "bundle exec ruby script/crawler"
     depends_on:
       - db
     restart: always

