# SQLite version 3.x
development:
  adapter: sqlite3
  encoding: utf8
  database: db/development.sqlite3
  timeout: 5000

# Do not set this db to the same as development or production.
test:
  adapter: sqlite3
  encoding: utf8
  database: db/test.sqlite3
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
